# Generated by Django 4.1.2 on 2024-07-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('sueldo', models.CharField(max_length=7)),
                ('activo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prod', models.CharField(max_length=60)),
                ('cantidad_prod', models.CharField(max_length=30)),
                ('almacenaje', models.CharField(max_length=50)),
            ],
        ),
    ]
